import random
l=[]
for liczba in range(11):
    l.append("liczba0","liczba1","liczba2","liczba3","liczba4","liczba5","liczba6","liczba7","liczba8","liczba9")
random.randrange(100)
liczba0=random.random()
print(liczba0)
liczba1=random.random()
print(liczba1)
liczba2=random.random()
print(liczba2)
liczba3=random.random()
print(liczba3)
liczba4=random.random()
print(liczba4)
liczba5=random.random()
print(liczba5)
liczba6=random.random()
print(liczba6)
liczba7=random.random()
print(liczba7)
liczba8=random.random()
print(liczba8)
liczba9=random.random()
print(liczba9)